export const metadata = { title: "Privacy Policy - If I Was There" };

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-12 text-sm text-gray-300 leading-relaxed space-y-6">
      <h1 className="text-2xl font-bold text-white">Privacy Policy</h1>
      <p className="text-gray-500">Last updated: June 15, 2026</p>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">1. Data We Collect</h2>
        <p>
          When you use If I Was There to generate an image, we temporarily process
          the selfie photo you upload. This photo is sent directly to our AI
          provider for generation and is <strong>not stored</strong> on our
          servers.
        </p>
        <p>
          The generated output image is stored for <strong>3 days</strong> and
          then automatically deleted. No other user data is stored.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">2. Data We Do NOT Collect</h2>
        <ul className="list-disc list-inside space-y-1">
          <li>We do not store your uploaded selfie photos</li>
          <li>We do not collect your name, email, or phone number</li>
          <li>We do not use cookies or tracking</li>
          <li>We do not share data with advertisers</li>
          <li>We do not use facial recognition or biometric analysis</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">3. AI-Generated Content</h2>
        <p>
          All images generated by this app are clearly labeled as AI-generated.
          We use third-party AI services to generate images; please refer to
          their respective privacy policies for details on how they process
          image data during generation.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">4. Third-Party Services</h2>
        <ul className="list-disc list-inside space-y-1">
          <li><strong>Google OAuth</strong> — used only for administrator login. Standard Google Privacy Policy applies.</li>
          <li><strong>AI Generation API</strong> — selfie images are transmitted to our AI provider for processing. Images are not retained by them.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">5. Data Retention</h2>
        <p>
          Generated images are stored for <strong>3 days</strong> to allow you
          to download and share them. After 3 days, they are permanently deleted.
          No other user data is retained.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-white">6. Contact</h2>
        <p>
          If you have questions about this privacy policy, contact us at{" "}
          <a href="mailto:zhengbijun123@gmail.com" className="text-cyan-400 hover:underline">
            zhengbijun123@gmail.com
          </a>.
        </p>
      </section>
    </div>
  );
}
